
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Video Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Video Link", name: "video", widget: "string" }

  - name: "color_grading"
    label: "Color Grading"
    folder: "grading"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "RAW Image", name: "raw", widget: "image" }
      - { label: "GRADED Image", name: "graded", widget: "image" }

  - name: "photos"
    label: "Photo Gallery"
    folder: "photos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title (optional)", name: "title", widget: "string", required: false }
      - { label: "Images", name: "gallery", widget: "list", field: { label: "Image", name: "image", widget: "image" } }

  - name: "home"
    label: "Home Page"
    files:
      - file: "index.html"
        label: "Home Content"
        name: "home"
        fields:
          - { label: "Intro Text", name: "intro", widget: "text" }
          - { label: "Reel Video Link", name: "reel", widget: "string" }
          - { label: "Footer Email", name: "email", widget: "string" }
          - { label: "Footer Phone", name: "phone", widget: "string" }
